### ISSUE TITLE
sectionFinder error thrown when trying to render

### ISSUE THREAD

**Issue by iansan5653** [ryanluker/vscode-coverage-gutters#203] opened 2019-01-10 16:10 UTC
When I click the "Watch" button, the extension runs until it outputs the following error message:
```
[1547136458662][coverageservice]: READY
[1547136458662][coverageservice]: RENDERING
[1547136469701][sectionFinder][path]__init__.py[error]Error: Found too many files with partial path __init__.py
```
At this point, **all** extensions in VSCode stop working until I reload the program. 

All of my settings for the extension are stylistic:
```
    "coverage-gutters.showGutterCoverage": false,
    "coverage-gutters.showLineCoverage": true,
    "coverage-gutters.partialHighlightDark": "rgba(121, 86, 10, 0.0)",
    "coverage-gutters.partialHighlightLight": "rgba(220, 213, 143, 0.2)",
    "coverage-gutters.noHighlightDark": "rgba(121, 31, 10, 0.2)",
    "coverage-gutters.noHighlightLight": "rgba(220, 143, 143, 0.2)",
    "coverage-gutters.highlightdark": "rgba(45, 121, 10, 0.0)",
    "coverage-gutters.highlightlight": "rgba(166, 220, 142, 0.0)",
    "coverage-gutters.showRulerCoverage": true,
```

Here's my system info:
Version: 1.31.0-insider (user setup)
Commit: 344f4fa361e098b49aeace9602e89275fbbd17bf
Date: 2019-01-10T06:21:21.472Z
Electron: 3.0.13
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.15063

I am happy to provide more information, but I am not sure what is relevant. My coverage file is kept in the project root as `cov.xml`, and this project does have modules and submodules with `__init.py__` files.

**Comment by ryanluker** [comment] 2019-01-20 18:04
@iansan5653 thanks for submitting an issue! Sorry to hear about the issues you are encountering, the extension locking up your vscode is not the intention, heh. Lets try to diagnose the problem...
1) Are you able to checkout this project and display coverage for the example python project?
2) Can you provide the cov.xml and or a subsection so that we can see if there are any obvious errors?
3) Which type of coverage file are you generating? (clover, cobertura, lcov, etc)
4) Have you tried adding folders to the ignore setting? (by default venv is ignored but depending on your dependencies it might be looking into those as well...) https://github.com/ryanluker/vscode-coverage-gutters/blob/master/package.json#L122

**Comment by iansan5653** [comment] 2019-01-25 14:10
Actually, there is one improvement - it doesn't seem to lock up all the other extensions on failure now.

**Comment by ryanluker** [comment] 2019-02-04 16:39
@iansan5653 thanks for the extra info, I will try to look into this within a week.

**Comment by ryanluker** [comment] 2019-02-17 19:34
@iansan5653 I started looking into this but couldnt find anything obviously wrong but one thing of note is that those errors (more like warnings in this case) are caused by the filename / path not resolving to an absolute value (https://gist.github.com/iansan5653/c6dc8b0d2a79249d9f2b87a8539a01ea#file-cov-xml-L45 vs https://github.com/ryanluker/vscode-coverage-gutters/blob/master/example/python/cov.xml#L19). 

This by itself shouldnt cause the other coverages to not be shown and you did confirm that the example python project works fine. Lets try a few more things...

1) Can you try modifing `py.test {FOLDER} --cov-report xml:cov.xml --cov {FOLDER}` to use a folder that is higher up to try to get the file paths to include more details?

2) this looks similar to a previous issue we thought we fixed via the cobertura plugin, https://github.com/ryanluker/vscode-coverage-gutters/issues/133 maybe there is something we missed if you are still having this problem.

3) this issue looks to be very similar to what is happening to you https://bitbucket.org/ned/coveragepy/issues/526/generated-xml-invalid-paths-for-cobertura
I might look through the cobertura plugin again and see if they are not properly combining the source to the file names...

**Comment by s-weigand** [comment] 2019-02-20 17:48
Had the same problem and using:
```json
"coverage-gutters.ignoredPathGlobs": 
  "**/{node_modules,venv,vendor,.tox,.pytest_cache,__pycache__}/**",
```
did the trick for me.

**Comment by gsemet** [comment] 2019-02-22 14:03
Hi. pipenv user here. Same issue:
- `pipenv run py.test mymodule --cov-report xml:cov.xml --cov mymodule` where mymodule is in the name of the first level of module. Using "." is not possible since it finds `.venv` etc and so pytest is too long
- trick from @s-weigand does not work, eventhough I thing .venv should be removed indeed from the current folder.

For me should ignore something like:
```
**/{node_modules,venv,.venv,vendor,.tox,.pytest_cache,__pycache__,.mypy_cache,build,.git,dist}/**
```

**Comment by iansan5653** [comment] 2019-02-22 17:55
@ryanluker 

Trying it after running `py.test --cov-report xml:cov.xml --cov` in the parent folder yielded the following logs:

```
[1550857931867][coverageservice]: READY
[1550857931868][coverageservice]: RENDERING
[1550857933134][sectionFinder][path]C:/Users/isanders/AppData/Roaming/Python/Python37/site-packages/six.py[error]Error: Found too many files with partial path C:/Users/isanders/AppData/Roaming/Python/Python37/site-packages/six.py
[1550857934452][sectionFinder][path]C:/Users/isanders/AppData/Roaming/Python/Python37/site-packages/colorama/ansitowin32.py[error]Error: Found too many files with partial path C:/Users/isanders/AppData/Roaming/Python/Python37/site-packages/colorama/ansitowin32.py
[1550857937680][sectionFinder][path]C:/Users/isanders/AppData/Roaming/Python/Python37/site-packages/colorama/win32.py[error]Error: Found too many files with partial path C:/Users/isanders/AppData/Roaming/Python/Python37/site-packages/colorama/win32.py
[1550857939932][sectionFinder][path]C:/Users/isanders/AppData/Roaming/Python/Python37/site-packages/colorama/winterm.py[error]Error: Found too many files with partial path C:/Users/isanders/AppData/Roaming/Python/Python37/site-packages/colorama/winterm.py
[1550857942049][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/__init__.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/__init__.py
[1550857943572][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/_config.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/_config.py
[1550857945242][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/base.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/base.py
[1550857946906][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/exceptions.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/exceptions.py
[1550857948571][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/isotonic.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/isotonic.py
[1550857950096][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/__check_build/__init__.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/__check_build/__init__.py
[1550857951664][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/cluster/__init__.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/cluster/__init__.py
[1550857953303][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/cluster/_feature_agglomeration.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/cluster/_feature_agglomeration.py
[1550857954987][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/cluster/affinity_propagation_.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/cluster/affinity_propagation_.py
[1550857956516][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/cluster/bicluster.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/cluster/bicluster.py
[1550857958129][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/cluster/birch.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/cluster/birch.py
[1550857959720][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/cluster/dbscan_.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/cluster/dbscan_.py
[1550857961370][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/cluster/hierarchical.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/cluster/hierarchical.py
[1550857963305][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/cluster/k_means_.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/cluster/k_means_.py
[1550857964883][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/cluster/mean_shift_.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/cluster/mean_shift_.py
[1550857966536][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/cluster/optics_.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/cluster/optics_.py
[1550857968294][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/cluster/spectral.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/cluster/spectral.py
[1550857969919][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/decomposition/__init__.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/decomposition/__init__.py
[1550857971519][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/decomposition/base.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/decomposition/base.py
[1550857973147][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/decomposition/dict_learning.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/decomposition/dict_learning.py
[1550857975002][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/decomposition/factor_analysis.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/decomposition/factor_analysis.py
[1550857976865][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/decomposition/fastica_.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/decomposition/fastica_.py
[1550857978755][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/decomposition/incremental_pca.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/decomposition/incremental_pca.py
[1550857980318][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/decomposition/kernel_pca.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/decomposition/kernel_pca.py
[1550857982504][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/decomposition/nmf.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/decomposition/nmf.py
[1550857984566][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/decomposition/online_lda.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/decomposition/online_lda.py
[1550857986222][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/decomposition/pca.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/decomposition/pca.py
[1550857988010][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/decomposition/sparse_pca.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/decomposition/sparse_pca.py
[1550857989773][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/decomposition/truncated_svd.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/decomposition/truncated_svd.py
[1550857991504][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/__init__.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/__init__.py
[1550857993448][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/six.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/six.py
[1550857995058][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/__init__.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/__init__.py
[1550857996792][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/_compat.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/_compat.py
[1550857998556][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/_memmapping_reducer.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/_memmapping_reducer.py
[1550858000159][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/_memory_helpers.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/_memory_helpers.py
[1550858002068][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/_multiprocessing_helpers.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/_multiprocessing_helpers.py
[1550858003689][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/_parallel_backends.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/_parallel_backends.py
[1550858005478][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/_store_backends.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/_store_backends.py
[1550858007254][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/backports.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/backports.py
[1550858009001][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/compressor.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/compressor.py
[1550858010915][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/disk.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/disk.py
[1550858012575][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/executor.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/executor.py
[1550858014225][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/format_stack.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/format_stack.py
[1550858015935][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/func_inspect.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/func_inspect.py
[1550858017684][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/hashing.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/hashing.py
[1550858019287][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/logger.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/logger.py
[1550858020993][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/memory.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/memory.py
[1550858022692][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/my_exceptions.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/my_exceptions.py
[1550858024301][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/numpy_pickle.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/numpy_pickle.py
[1550858025989][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/numpy_pickle_compat.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/numpy_pickle_compat.py
[1550858027684][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/numpy_pickle_utils.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/numpy_pickle_utils.py
[1550858029292][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/parallel.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/parallel.py
[1550858030995][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/pool.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/pool.py
[1550858032748][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/externals/__init__.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/externals/__init__.py
[1550858034390][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/externals/cloudpickle/__init__.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/externals/cloudpickle/__init__.py
[1550858036034][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py
[1550858037735][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/externals/loky/__init__.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/externals/loky/__init__.py
[1550858039351][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/externals/loky/_base.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/externals/loky/_base.py
[1550858041376][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/externals/loky/cloudpickle_wrapper.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/externals/loky/cloudpickle_wrapper.py
[1550858043050][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/externals/loky/process_executor.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/externals/loky/process_executor.py
[1550858044723][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/externals/loky/reusable_executor.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/externals/loky/reusable_executor.py
[1550858046362][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/externals/loky/backend/__init__.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/externals/loky/backend/__init__.py
[1550858048355][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/externals/loky/backend/_win_reduction.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/externals/loky/backend/_win_reduction.py
[1550858050050][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/externals/loky/backend/compat.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/externals/loky/backend/compat.py
[1550858051747][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/externals/loky/backend/compat_win32.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/externals/loky/backend/compat_win32.py
[1550858053336][sectionFinder][path]C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/externals/loky/backend/context.py[error]Error: Found too many files with partial path C:/Users/isanders/Documents/scikit-learn/scikit-learn/sklearn/externals/joblib/externals/loky/backend/context.py
........
```

They keep going like that for a while.

**Comment by iansan5653** [comment] 2019-02-22 18:06
I am not using pipenv (or any virtual environments) by the way.

**Comment by iansan5653** [comment] 2019-03-22 13:46
Any updates? I really miss this feature.

**Comment by ryanluker** [comment] 2019-03-30 20:59
@iansan5653 I am getting back into putting some more time into this project so I will investigate this a bit again today.
@s-weigand Sorry to hear you are having similar issues can you confirm the same 1, 2 and 3 in https://github.com/ryanluker/vscode-coverage-gutters/issues/203#issuecomment-455888360?

**Comment by ryanluker** [comment] 2019-03-30 21:27
@s-weigand @iansan5653 might have figured out how to fix this, please try out the vsix below and let me know how it works!

[vscode-coverage-gutters-2.4.0.zip](https://github.com/ryanluker/vscode-coverage-gutters/files/3025983/vscode-coverage-gutters-2.4.0.zip)

**Comment by ryanluker** [comment] 2019-04-07 15:54
closing this as it will go out with the next release, thanks again for submitting an issue!

**Closed by ryanluker** 2019-04-07 15:54 UTC
Labels: bug
