### ISSUE TITLE
Correctly shows coverage only for the first file in a PHP project

### ISSUE THREAD

**Issue by VVatashi** [ryanluker/vscode-coverage-gutters#157] opened 2018-08-04 05:23 UTC
Hello, I have tried this extension to show the line coverage in my project. It looks like it works for the first PHP file in the project. But when I select any other file, unfortunately, it seems that it continues to show the coverage of the first file.
I have generated a code coverage file with the PHPUnit with the coverage-clover option.

- VS Code: 1.25.1
- Coverage Gutters: 2.1.0
- PHPUnit: 7.2.7

The coverage-gutters log looks like:
```
[1533358148956][coverageservice]: INITIALIZING
[1533358162996][coverageservice]: LOADING
[1533358163012][coverageservice]: Loading 1 file(s)
[1533358163052][coverageservice]: Caching 3 coverage(s)
[1533358163052][coverageservice]: READY
[1533358163052][coverageservice]: RENDERING
[1533358163053][renderer][section file path]: <path to the first file in the project>
[1533358163053][coverageservice]: READY
[1533358170943][coverageservice]: RENDERING
[1533358170944][coverageservice]: READY
[1533358170998][coverageservice]: RENDERING
[1533358170998][renderer][section file path]: <path to the first file in the project>
[1533358171053][coverageservice]: READY
[1533358192472][coverageservice]: RENDERING
[1533358192472][coverageservice]: READY
[1533358192520][coverageservice]: RENDERING
[1533358192520][renderer][section file path]: <path to the first file in the project>
...
```

**Comment by ryanluker** [comment] 2018-08-04 21:58
@VVatashi thanks for submitting an issue. I was not able to reproduce this locally :thinking: . I added some more files to the example project and then all rendered different coverages fine.
![screenshot from 2018-08-04 14-56-55](https://user-images.githubusercontent.com/1335972/43680777-cd5a3f7a-97f6-11e8-9869-a3f36d4bd1a4.png)

**Comment by VVatashi** [comment] 2018-08-05 04:45
With my project, both as a folder and as a workspace, it seems that it not works properly.
But now I have cloned example project, added more classes and tests, and it works.
So, maybe something is wrong with my project... I will try to figure out what is difference.

**Comment by ryanluker** [comment] 2018-08-05 19:37
@VVatashi this sounds related to #155 once the bugfix release (2.1.1) is out you should try again 😄

**Comment by ryanluker** [comment] 2018-08-06 23:51
@VVatashi 2.1.1 has been released, going to close this ticket but we can reopen it if you found the issue isnt gone.

**Closed by ryanluker** 2018-08-06 23:51 UTC
Labels: bug
