### ISSUE TITLE
Preview Coverage Report doesn't work

### ISSUE THREAD

**Issue by RensDimmendaal** [ryanluker/vscode-coverage-gutters#275] opened 2020-08-27 11:50 UTC
**Bug:**
When I open the "Preview Coverage Report" I don't see the actual report but I get this template file.
The gutter coverage works great though 👍 

**To Reproduce**
```python
pytest --cov=mypackage --cov-report=xml:cov.xml tests/
```

**Expected behaviour**
I expect to see the actual coverage report

**Screenshots**
![image](https://user-images.githubusercontent.com/9828683/91438618-f0f5b280-e86b-11ea-86b5-c8d4435b005e.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Extension Version 2.6.0
- VSCode version: 1.49.0-insider

**Comment by ryanluker** [comment] 2020-10-11 20:16
@RensDimmendaal Thanks for submitting an issue!
I wasn't able to reproduce this with the latest version of vscode and the example project 🤔 
![image](https://user-images.githubusercontent.com/1335972/95689152-c4032200-0bc3-11eb-8722-7f7a0d0de390.png)

Usually this is an issue with the generated html file, can you confirm that you have the latest coverage py package?

**Comment by ryanluker** [comment] 2020-12-20 19:32
Closing due to staleness, happy to reopen!

**Closed by ryanluker** 2020-12-20 19:32 UTC
Labels: investigating

**Comment by cdonnellytx** [comment] 2021-01-29 18:12
I'm seeing this issue as well and haven't been able to correct it.  Gutters work fine, the report is the only issue.

- OS: Windows 10 20H2
- VS Code 1.52.1
- Coverage Gutters 2.6.0
- Python 3.8.6 (venv)
- pytest 6.2.2
- coverage 5.4
- pytest-cov 2.11.1

Is there anything I can do like turning up logging, etc.? Any other troubleshooting?

**Comment by ryanluker** [comment] 2021-01-31 18:04
@cdonnellytx There is a couple things you can try.
1) Try out the example project and see if you can preview that html? (screenshot 1)
https://github.com/ryanluker/vscode-coverage-gutters/tree/master/example/node

2) Can you check if there is any logging errors around the webview in the gutters log? (screenshot 2)

3) We have some security work being completed by @Kaytbode that might help with your issue if it is a security bit that is preventing the preview from loading 🤔 
https://github.com/ryanluker/vscode-coverage-gutters/issues/237

![Screenshot 2021-01-31 100201](https://user-images.githubusercontent.com/1335972/106393336-63cf0080-63ab-11eb-9765-54cf0be176ff.png)

![Screenshot 2021-01-31 100101](https://user-images.githubusercontent.com/1335972/106393337-64679700-63ab-11eb-87bf-7f27e0b95c54.png)

**Comment by cdonnellytx** [comment] 2021-02-12 23:00
The preview works for me in the Node sample project, but not the Python one.

A couple of things I found out by hacking some additional logging into the extension:

- It's explicitly looking for an HTML file under `${workspaceRoot}/**/coverage/**/index.html`.  If your test generator doesn't output HTML you won't have a file to view.
- If you set up a Python venv and install `pytest-cov`, it installs the `coverage` package at `${venv}/Lib/site-packages/coverage`.  The package includes a template file at `${venv}/Lib/site-packages/coverage/htmlfiles/index.html`.  This matches the wildcard above, and is what is showing up in the webview.  
- If you do _not_ set up a Python venv, it won't find the coverage file template, because it is in a shared location (e.g. `%LOCALAPPDATA%\programs\python\python39\lib\site-packages\coverage\htmlfiles\index.html`).

Fortunately it looks like I can get pytest to generate both HTML and XML with the following in `pytest.ini`:

```ini
[pytest]
# ...
addopts =
    --cov=python/foobar
    --cov-report xml
    --cov-report html:coverage/xyz
```

The HTML report defaults to `${workspaceRoot}/htmlcov/`.  By setting it above, I finally get a prompt to choose between the venv and it:

![image](https://user-images.githubusercontent.com/183046/107830914-6e49ac80-6d52-11eb-8459-8283c6d42350.png)

Which lets me select the correct report:
![image](https://user-images.githubusercontent.com/183046/107831138-fe87f180-6d52-11eb-80bf-18bf67fdbb9d.png)

Ideally the search would exclude the venv directory (if there is one) under the workspace.  (Or maybe I'm not supposed to put it there -- I'm fairly new to Python and so I don't know if I should be creating the venv outside the workspace tree.)  This at least explains everything, though.

**Comment by cdonnellytx** [comment] 2021-02-12 23:10
Found the `coverage-gutters.ignoredPathGlobs` setting and was able to get rid of it searching my venv.

Looks like it excludes `venv` but not `.venv` by default.  [Python venv docs](https://docs.python.org/3/library/venv.html) use that as a "common" name for the directory; you might want to add it to the default ignored globs...

**Comment by ryanluker** [comment] 2021-02-13 18:55
@cdonnellytx Good find, I will add that to the defaults!
You can find that addition here https://github.com/ryanluker/vscode-coverage-gutters/commit/f71d17c62e1095334d6366d8b3b82aa723f8e8b1 .

Regarding the virtual env, and where it should be located, I usually put mine in the root (C:\ or ~/ depending on the OS).
Having it in the project isn't wrong either though 🤔 .
