### ISSUE TITLE
Coverage "gutter" not showing, "line" and "ruler" OK

### ISSUE THREAD

**Issue by denisrossetre** [ryanluker/vscode-coverage-gutters#407] opened 2023-05-12 07:42 UTC
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

1. Open a file part of the coverage tests
2. Click on the "Watch" status bar button
3. The "watch" transforms into "X % coverage" 
4. The coverage markers show up in line and ruler forms, but not in gutter form.

I've checked the "coverage-gutters" output window, everything seems fine.

**Expected behaviour**

Coverage that displays in the gutter

**Screenshots**
![image](https://github.com/ryanluker/vscode-coverage-gutters/assets/129750228/ae34c34e-d2aa-4645-bf5e-d43e2c53dbf9)
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Extension Version v2.10.4
 - VSCode Version 1.78.2

**Comment by denisrossetre** [comment] 2023-05-12 07:45
The problem does not happen with a blank profile created with the "Python" defaults.

This hints at an incompatibility with another VS Code extension.

![image](https://github.com/ryanluker/vscode-coverage-gutters/assets/129750228/3cfe4a82-31bf-412a-b166-3b4373267a1d)

**Comment by denisrossetre** [comment] 2023-05-12 07:54
I haven't been able to identify which extension causes the problem, I'm restarting work with a blank profile and will update if I find anything.

**Comment by SimonKagstrom** [comment] 2023-05-12 08:51
The gutter line seen in your last image is much thinner than it used to be. I see this since (I think) the last vscode update, and it makes it very hard to use the gutter display to actually see the coverage.

Perhaps a separate issue, but making it wider would improve the usability again I think

**Comment by denisrossetre** [comment] 2023-05-12 08:53
Thanks @SimonKagstrom . Btw, your extension is very useful to work on improving code coverage where it matters.

... and indeed the problem happened after the last VS Code updates. In the meantime, I added extra extensions. If I can find something more specific, I'll update this issue.

**Comment by SimonKagstrom** [comment] 2023-05-12 08:56
The credit goes to @ryanluker for the extension :-)

**Comment by ryanluker** [comment] 2023-05-12 22:22
@denisrossetre Thanks for the ticket! (And the shoutout @SimonKagstrom 👍🏻)

I do think we are on the right track here, and something new with the latest vscode has shrunk the available gutter space we have for decoration icons 😢. Even if I double the size of the svg width it doesn't do anything, sadly...

(Note: the gutter is actually a SVG file while the line and ruler are just hex colours)

#### Current svg width
![Screenshot from 2023-05-12 15-13-15](https://github.com/ryanluker/vscode-coverage-gutters/assets/1335972/0ebfbed4-2ec1-44de-8a32-f1db99ebd626)

#### Doubled svg width
![Screenshot from 2023-05-12 15-17-29](https://github.com/ryanluker/vscode-coverage-gutters/assets/1335972/77040d2c-0766-4bad-b7ea-bd641e443ae2)

**Comment by vkbo** [comment] 2023-06-09 13:19
Well, in the new version of VSCode that arrived today, the wide gutter seems to be working again 😄 

![image](https://github.com/ryanluker/vscode-coverage-gutters/assets/1619840/27fa8c16-a1ce-4c6c-86ff-9bcefa99b760)

**Comment by ryanluker** [comment] 2023-06-20 19:11
@vkbo interesting, maybe a regression in the vscode styling then 🤔 closing for now.

**Closed by ryanluker** 2023-06-20 19:11 UTC
Labels: upstream
