### ISSUE TITLE
Line coverage not displaying with latest release.

### ISSUE THREAD

**Issue by Syntactical01** [ryanluker/vscode-coverage-gutters#255] opened 2020-02-24 13:36 UTC
**Describe the bug**
In the newest version of coverage gutters the lines in my python files are not being highlighted.
If I downgrade to version `2.0.0` it works as expected (lines are highlighted) but with the newest version (`2.4.3`) and several versions prior, the lines won't highlight. Appears to be related to a prior issue that I can no longer find listed in Issues :P.

**Expected behaviour & Screenshots**
Easier shown with screen shots:

Version `2.4.3`:
![image](https://user-images.githubusercontent.com/46199814/75156363-95d5de00-56d7-11ea-87c2-30ed65656a87.png)

Version `2.0.0`:
![image](https://user-images.githubusercontent.com/46199814/75156433-c0c03200-56d7-11ea-9157-836692b8c385.png)

**Desktop:**
 - OS: MacOS
 - VSCode Version: 1.42.1

**Additional context**
The output for the cover-gutters appears to be correct:
```
[1582550627101][coverageservice]: INITIALIZING
[1582550634018][coverageservice]: LOADING
[1582550641655][coverageservice]: Loading 1 file(s)
[1582550641656][coverageservice]: Loaded 1 data file(s)
[1582550641683][coverageservice]: Caching 22 coverage(s)
[1582550641684][printDataCoverage]: Coverage -> 22
```
It sees the 22 files, however when I use version`2.0.0` the ouput also includes the following line when I look at the file:
```
[1582551137115][renderer][section file path]: aws_services/dynamodb_table.py [exactness score]: 33.33333333333333
```

`cov.xml` file is generated and exists at the root level of the project:
```
<?xml version="1.0" ?>
<coverage version="5.0.3" timestamp="1582550544418" lines-valid="625" lines-covered="581" line-rate="0.9296" branches-covered="0" branches-valid="0" branch-rate="0" complexity="0">
	<!-- Generated by coverage.py: https://coverage.readthedocs.io -->
	<!-- Based on https://raw.githubusercontent.com/cobertura/web/master/htdocs/xml/coverage-04.dtd -->
	<sources>
		<source>/src/skylab_api/src</source>
	</sources>
	<packages>
		<package name="." line-rate="0" branch-rate="0" complexity="0">
			<classes>
				<class name="__init__.py" filename="__init__.py" complexity="0" line-rate="1" branch-rate="0">
					<methods/>
					<lines/>
				</class>
				<class name="skylab_lambda.py" filename="skylab_lambda.py" complexity="0" line-rate="0" branch-rate="0">
					<methods/>
					<lines>
						<line number="5" hits="0"/>
						<line number="6" hits="0"/>
						<line number="9" hits="0"/>
						<line number="10" hits="0"/>
						<line number="15" hits="0"/>
						<line number="18" hits="0"/>
						<line number="19" hits="0"/>
						<line number="20" hits="0"/>
						<line number="22" hits="0"/>
						<line number="24" hits="0"/>
						<line number="26" hits="0"/>
						<line number="29" hits="0"/>
						<line number="41" hits="0"/>
						<line number="43" hits="0"/>
						<line number="45" hits="0"/>
						<line number="49" hits="0"/>
						<line number="50" hits="0"/>
						<line number="51" hits="0"/>
						<line number="52" hits="0"/>
						<line number="53" hits="0"/>
						<line number="55" hits="0"/>
						<line number="56" hits="0"/>
						<line number="60" hits="0"/>
						<line number="61" hits="0"/>
						<line number="63" hits="0"/>
						<line number="64" hits="0"/>
						<line number="68" hits="0"/>
						<line number="69" hits="0"/>
						<line number="75" hits="0"/>
						<line number="76" hits="0"/>
						<line number="80" hits="0"/>
						<line number="81" hits="0"/>
						<line number="82" hits="0"/>
						<line number="86" hits="0"/>
						<line number="87" hits="0"/>
					</lines>
				</class>
				<class name="skylab_service.py" filename="skylab_service.py" complexity="0" line-rate="0" branch-rate="0">
					<methods/>
					<lines>
						<line number="8" hits="0"/>
						<line number="16" hits="0"/>
						<line number="19" hits="0"/>
						<line number="21" hits="0"/>
					</lines>
				</class>
			</classes>
		</package>
		<package name="aws_services" line-rate="1" branch-rate="0" complexity="0">
			<classes>
				<class name="__init__.py" filename="aws_services/__init__.py" complexity="0" line-rate="1" branch-rate="0">
					<methods/>
					<lines>
						<line number="5" hits="1"/>
						<line number="6" hits="1"/>
						<line number="7" hits="1"/>
					</lines>
				</class>
				<class name="dynamo_transactions.py" filename="aws_services/dynamo_transactions.py" complexity="0" line-rate="1" branch-rate="0">
					<methods/>
					<lines>
						<line number="7" hits="1"/>
						<line number="8" hits="1"/>
						<line number="9" hits="1"/>
						<line number="14" hits="1"/>
						<line number="19" hits="1"/>
						<line number="20" hits="1"/>
						<line number="26" hits="1"/>
						<line number="29" hits="1"/>
						<line number="31" hits="1"/>
						<line number="37" hits="1"/>
						<line number="42" hits="1"/>
						<line number="43" hits="1"/>
						<line number="45" hits="1"/>
						<line number="59" hits="1"/>
						<line number="60" hits="1"/>
						<line number="61" hits="1"/>
						<line number="62" hits="1"/>
						<line number="63" hits="1"/>
						<line number="64" hits="1"/>
						<line number="66" hits="1"/>
						<line number="70" hits="1"/>
						<line number="81" hits="1"/>
						<line number="82" hits="1"/>
						<line number="88" hits="1"/>
						<line number="89" hits="1"/>
						<line number="93" hits="1"/>
						<line number="103" hits="1"/>
						<line number="104" hits="1"/>
						<line number="105" hits="1"/>
						<line number="107" hits="1"/>
						<line number="108" hits="1"/>
						<line number="109" hits="1"/>
						<line number="110" hits="1"/>
						<line number="113" hits="1"/>
						<line number="114" hits="1"/>
						<line number="117" hits="1"/>
						<line number="121" hits="1"/>
						<line number="123" hits="1"/>
						<line number="124" hits="1"/>
						<line number="127" hits="1"/>
						<line number="128" hits="1"/>
					</lines>
				</class>
				<class name="dynamodb_table.py" filename="aws_services/dynamodb_table.py" complexity="0" line-rate="1" branch-rate="0">
					<methods/>
					<lines>
						<line number="6" hits="1"/>
						<line number="7" hits="1"/>
						<line number="8" hits="1"/>
						<line number="9" hits="1"/>
						<line number="13" hits="1"/>
						<line number="14" hits="1"/>
						<line number="17" hits="1"/>
						<line number="18" hits="1"/>
						<line number="19" hits="1"/>
						<line number="22" hits="1"/>
						<line number="23" hits="1"/>
						<line number="29" hits="1"/>
						<line number="31" hits="1"/>
						<line number="33" hits="1"/>
						<line number="34" hits="1"/>
						<line number="36" hits="1"/>
						<line number="41" hits="1"/>
						<line number="44" hits="1"/>
						<line number="45" hits="1"/>
						<line number="46" hits="1"/>
						<line number="48" hits="1"/>
						<line number="74" hits="1"/>
						<line number="75" hits="1"/>
						<line number="76" hits="1"/>
						<line number="80" hits="1"/>
						<line number="84" hits="1"/>
						<line number="85" hits="1"/>
						<line number="86" hits="1"/>
						<line number="90" hits="1"/>
						<line number="95" hits="1"/>
						<line number="96" hits="1"/>
						<line number="98" hits="1"/>
						<line number="99" hits="1"/>
						<line number="100" hits="1"/>
						<line number="112" hits="1"/>
						<line number="113" hits="1"/>
						<line number="115" hits="1"/>
						<line number="126" hits="1"/>
						<line number="127" hits="1"/>
						<line number="142" hits="1"/>
						<line number="143" hits="1"/>
						<line number="145" hits="1"/>
						<line number="164" hits="1"/>
						<line number="169" hits="1"/>
						<line number="172" hits="1"/>
						<line number="174" hits="1"/>
						<line number="178" hits="1"/>
						<line number="191" hits="1"/>
						<line number="194" hits="1"/>
						<line number="197" hits="1"/>
						<line number="199" hits="1"/>
						<line number="206" hits="1"/>
						<line number="211" hits="1"/>
						<line number="212" hits="1"/>
						<line number="214" hits="1"/>
						<line number="218" hits="1"/>
						<line number="229" hits="1"/>
						<line number="230" hits="1"/>
						<line number="244" hits="1"/>
						<line number="245" hits="1"/>
						<line number="247" hits="1"/>
						<line number="248" hits="1"/>
						<line number="259" hits="1"/>
						<line number="277" hits="1"/>
						<line number="278" hits="1"/>
						<line number="283" hits="1"/>
					</lines>
				</class>
				<class name="s3_bucket.py" filename="aws_services/s3_bucket.py" complexity="0" line-rate="1" branch-rate="0">
					<methods/>
					<lines>
						<line number="6" hits="1"/>
						<line number="7" hits="1"/>
						<line number="8" hits="1"/>
						<line number="9" hits="1"/>
						<line number="16" hits="1"/>
						<line number="17" hits="1"/>
						<line number="18" hits="1"/>
						<line number="23" hits="1"/>
						<line number="25" hits="1"/>
						<line number="30" hits="1"/>
						<line number="33" hits="1"/>
						<line number="34" hits="1"/>
						<line number="35" hits="1"/>
						<line number="36" hits="1"/>
						<line number="37" hits="1"/>
						<line number="38" hits="1"/>
						<line number="43" hits="1"/>
						<line number="51" hits="1"/>
						<line number="52" hits="1"/>
						<line number="53" hits="1"/>
						<line number="54" hits="1"/>
						<line number="55" hits="1"/>
						<line number="56" hits="1"/>
						<line number="59" hits="1"/>
						<line number="60" hits="1"/>
						<line number="62" hits="1"/>
						<line number="63" hits="1"/>
						<line number="64" hits="1"/>
						<line number="66" hits="1"/>
						<line number="67" hits="1"/>
						<line number="68" hits="1"/>
						<line number="70" hits="1"/>
						<line number="90" hits="1"/>
						<line number="91" hits="1"/>
						<line number="92" hits="1"/>
						<line number="93" hits="1"/>
						<line number="94" hits="1"/>
						<line number="95" hits="1"/>
						<line number="96" hits="1"/>
						<line number="97" hits="1"/>
						<line number="98" hits="1"/>
						<line number="103" hits="1"/>
						<line number="105" hits="1"/>
						<line number="115" hits="1"/>
						<line number="116" hits="1"/>
						<line number="117" hits="1"/>
						<line number="132" hits="1"/>
						<line number="133" hits="1"/>
						<line number="134" hits="1"/>
						<line number="136" hits="1"/>
						<line number="141" hits="1"/>
						<line number="142" hits="1"/>
						<line number="143" hits="1"/>
						<line number="145" hits="1"/>
						<line number="146" hits="1"/>
					</lines>
				</class>
			</classes>
		</package>
		<package name="core" line-rate="0.9268" branch-rate="0" complexity="0">
			<classes>
				<class name="__init__.py" filename="core/__init__.py" complexity="0" line-rate="1" branch-rate="0">
					<methods/>
					<lines>
						<line number="4" hits="1"/>
						<line number="5" hits="1"/>
					</lines>
				</class>
				<class name="configure_logging.py" filename="core/configure_logging.py" complexity="0" line-rate="0.6" branch-rate="0">
					<methods/>
					<lines>
						<line number="5" hits="1"/>
						<line number="7" hits="1"/>
						<line number="9" hits="1"/>
						<line number="13" hits="0"/>
						<line number="14" hits="0"/>
					</lines>
				</class>
				<class name="decimal_encoder.py" filename="core/decimal_encoder.py" complexity="0" line-rate="0.8889" branch-rate="0">
					<methods/>
					<lines>
						<line number="6" hits="1"/>
						<line number="7" hits="1"/>
						<line number="12" hits="1"/>
						<line number="16" hits="1"/>
						<line number="17" hits="1"/>
						<line number="18" hits="1"/>
						<line number="19" hits="1"/>
						<line number="20" hits="1"/>
						<line number="21" hits="0"/>
					</lines>
				</class>
				<class name="decorators.py" filename="core/decorators.py" complexity="0" line-rate="1" branch-rate="0">
					<methods/>
					<lines>
						<line number="11" hits="1"/>
						<line number="22" hits="1"/>
						<line number="26" hits="1"/>
						<line number="29" hits="1"/>
						<line number="37" hits="1"/>
						<line number="38" hits="1"/>
						<line number="39" hits="1"/>
						<line number="41" hits="1"/>
						<line number="42" hits="1"/>
						<line number="43" hits="1"/>
						<line number="44" hits="1"/>
						<line number="45" hits="1"/>
						<line number="46" hits="1"/>
						<line number="47" hits="1"/>
						<line number="48" hits="1"/>
						<line number="49" hits="1"/>
						<line number="50" hits="1"/>
						<line number="51" hits="1"/>
						<line number="52" hits="1"/>
					</lines>
				</class>
				<class name="exceptions.py" filename="core/exceptions.py" complexity="0" line-rate="1" branch-rate="0">
					<methods/>
					<lines>
						<line number="4" hits="1"/>
						<line number="7" hits="1"/>
						<line number="10" hits="1"/>
						<line number="13" hits="1"/>
						<line number="16" hits="1"/>
						<line number="19" hits="1"/>
					</lines>
				</class>
			</classes>
		</package>
		<package name="core.enums" line-rate="1" branch-rate="0" complexity="0">
			<classes>
				<class name="__init__.py" filename="core/enums/__init__.py" complexity="0" line-rate="1" branch-rate="0">
					<methods/>
					<lines>
						<line number="4" hits="1"/>
						<line number="5" hits="1"/>
						<line number="6" hits="1"/>
					</lines>
				</class>
				<class name="content_types.py" filename="core/enums/content_types.py" complexity="0" line-rate="1" branch-rate="0">
					<methods/>
					<lines>
						<line number="11" hits="1"/>
						<line number="12" hits="1"/>
						<line number="14" hits="1"/>
						<line number="21" hits="1"/>
						<line number="22" hits="1"/>
						<line number="23" hits="1"/>
						<line number="24" hits="1"/>
						<line number="25" hits="1"/>
						<line number="26" hits="1"/>
						<line number="27" hits="1"/>
						<line number="28" hits="1"/>
						<line number="29" hits="1"/>
						<line number="30" hits="1"/>
						<line number="31" hits="1"/>
						<line number="32" hits="1"/>
						<line number="33" hits="1"/>
						<line number="34" hits="1"/>
						<line number="35" hits="1"/>
						<line number="36" hits="1"/>
						<line number="37" hits="1"/>
						<line number="38" hits="1"/>
						<line number="39" hits="1"/>
						<line number="40" hits="1"/>
						<line number="41" hits="1"/>
						<line number="42" hits="1"/>
						<line number="44" hits="1"/>
						<line number="45" hits="1"/>
						<line number="49" hits="1"/>
						<line number="51" hits="1"/>
						<line number="52" hits="1"/>
						<line number="56" hits="1"/>
						<line number="58" hits="1"/>
						<line number="59" hits="1"/>
						<line number="63" hits="1"/>
						<line number="65" hits="1"/>
						<line number="66" hits="1"/>
						<line number="70" hits="1"/>
						<line number="72" hits="1"/>
						<line number="73" hits="1"/>
						<line number="77" hits="1"/>
						<line number="79" hits="1"/>
						<line number="80" hits="1"/>
						<line number="84" hits="1"/>
						<line number="86" hits="1"/>
						<line number="87" hits="1"/>
						<line number="91" hits="1"/>
						<line number="93" hits="1"/>
						<line number="94" hits="1"/>
						<line number="98" hits="1"/>
						<line number="100" hits="1"/>
						<line number="101" hits="1"/>
						<line number="105" hits="1"/>
						<line number="107" hits="1"/>
						<line number="108" hits="1"/>
						<line number="112" hits="1"/>
						<line number="114" hits="1"/>
						<line number="115" hits="1"/>
						<line number="119" hits="1"/>
						<line number="121" hits="1"/>
						<line number="122" hits="1"/>
						<line number="126" hits="1"/>
						<line number="128" hits="1"/>
						<line number="129" hits="1"/>
						<line number="133" hits="1"/>
						<line number="135" hits="1"/>
						<line number="136" hits="1"/>
						<line number="140" hits="1"/>
						<line number="142" hits="1"/>
						<line number="143" hits="1"/>
						<line number="147" hits="1"/>
						<line number="149" hits="1"/>
						<line number="150" hits="1"/>
						<line number="154" hits="1"/>
						<line number="156" hits="1"/>
						<line number="157" hits="1"/>
						<line number="161" hits="1"/>
						<line number="163" hits="1"/>
						<line number="164" hits="1"/>
						<line number="168" hits="1"/>
						<line number="170" hits="1"/>
						<line number="171" hits="1"/>
						<line number="175" hits="1"/>
						<line number="177" hits="1"/>
						<line number="178" hits="1"/>
						<line number="182" hits="1"/>
						<line number="184" hits="1"/>
						<line number="185" hits="1"/>
						<line number="189" hits="1"/>
						<line number="191" hits="1"/>
						<line number="192" hits="1"/>
						<line number="196" hits="1"/>
					</lines>
				</class>
				<class name="enum.py" filename="core/enums/enum.py" complexity="0" line-rate="1" branch-rate="0">
					<methods/>
					<lines>
						<line number="7" hits="1"/>
						<line number="13" hits="1"/>
						<line number="18" hits="1"/>
						<line number="24" hits="1"/>
						<line number="26" hits="1"/>
						<line number="30" hits="1"/>
						<line number="32" hits="1"/>
						<line number="36" hits="1"/>
						<line number="50" hits="1"/>
						<line number="62" hits="1"/>
						<line number="63" hits="1"/>
						<line number="68" hits="1"/>
						<line number="72" hits="1"/>
					</lines>
				</class>
				<class name="regex_expressions.py" filename="core/enums/regex_expressions.py" complexity="0" line-rate="1" branch-rate="0">
					<methods/>
					<lines>
						<line number="12" hits="1"/>
						<line number="13" hits="1"/>
						<line number="15" hits="1"/>
						<line number="22" hits="1"/>
						<line number="23" hits="1"/>
						<line number="24" hits="1"/>
						<line number="25" hits="1"/>
						<line number="26" hits="1"/>
						<line number="28" hits="1"/>
						<line number="29" hits="1"/>
						<line number="35" hits="1"/>
						<line number="37" hits="1"/>
						<line number="38" hits="1"/>
						<line number="46" hits="1"/>
						<line number="48" hits="1"/>
						<line number="49" hits="1"/>
						<line number="58" hits="1"/>
						<line number="60" hits="1"/>
						<line number="61" hits="1"/>
						<line number="69" hits="1"/>
						<line number="71" hits="1"/>
						<line number="72" hits="1"/>
						<line number="79" hits="1"/>
					</lines>
				</class>
				<class name="response_codes.py" filename="core/enums/response_codes.py" complexity="0" line-rate="1" branch-rate="0">
					<methods/>
					<lines>
						<line number="11" hits="1"/>
						<line number="12" hits="1"/>
						<line number="14" hits="1"/>
						<line number="20" hits="1"/>
						<line number="21" hits="1"/>
						<line number="22" hits="1"/>
						<line number="23" hits="1"/>
						<line number="24" hits="1"/>
						<line number="25" hits="1"/>
						<line number="26" hits="1"/>
						<line number="27" hits="1"/>
						<line number="28" hits="1"/>
						<line number="29" hits="1"/>
						<line number="30" hits="1"/>
						<line number="31" hits="1"/>
						<line number="32" hits="1"/>
						<line number="33" hits="1"/>
						<line number="34" hits="1"/>
						<line number="35" hits="1"/>
						<line number="36" hits="1"/>
						<line number="37" hits="1"/>
						<line number="38" hits="1"/>
						<line number="39" hits="1"/>
						<line number="40" hits="1"/>
						<line number="41" hits="1"/>
						<line number="42" hits="1"/>
						<line number="43" hits="1"/>
						<line number="44" hits="1"/>
						<line number="45" hits="1"/>
						<line number="46" hits="1"/>
						<line number="47" hits="1"/>
						<line number="48" hits="1"/>
						<line number="49" hits="1"/>
						<line number="50" hits="1"/>
						<line number="51" hits="1"/>
						<line number="52" hits="1"/>
						<line number="53" hits="1"/>
						<line number="54" hits="1"/>
						<line number="55" hits="1"/>
						<line number="56" hits="1"/>
						<line number="57" hits="1"/>
						<line number="58" hits="1"/>
						<line number="59" hits="1"/>
						<line number="60" hits="1"/>
						<line number="61" hits="1"/>
						<line number="62" hits="1"/>
						<line number="63" hits="1"/>
						<line number="64" hits="1"/>
						<line number="65" hits="1"/>
						<line number="66" hits="1"/>
						<line number="67" hits="1"/>
						<line number="68" hits="1"/>
						<line number="69" hits="1"/>
						<line number="70" hits="1"/>
						<line number="71" hits="1"/>
						<line number="72" hits="1"/>
						<line number="73" hits="1"/>
						<line number="76" hits="1"/>
						<line number="77" hits="1"/>
						<line number="84" hits="1"/>
						<line number="86" hits="1"/>
						<line number="87" hits="1"/>
						<line number="94" hits="1"/>
						<line number="96" hits="1"/>
						<line number="97" hits="1"/>
						<line number="105" hits="1"/>
						<line number="107" hits="1"/>
						<line number="108" hits="1"/>
						<line number="114" hits="1"/>
						<line number="116" hits="1"/>
						<line number="117" hits="1"/>
						<line number="127" hits="1"/>
						<line number="129" hits="1"/>
						<line number="130" hits="1"/>
						<line number="141" hits="1"/>
						<line number="143" hits="1"/>
						<line number="144" hits="1"/>
						<line number="152" hits="1"/>
						<line number="154" hits="1"/>
						<line number="155" hits="1"/>
						<line number="163" hits="1"/>
						<line number="165" hits="1"/>
						<line number="166" hits="1"/>
						<line number="173" hits="1"/>
						<line number="175" hits="1"/>
						<line number="176" hits="1"/>
						<line number="183" hits="1"/>
						<line number="185" hits="1"/>
						<line number="186" hits="1"/>
						<line number="195" hits="1"/>
						<line number="197" hits="1"/>
						<line number="198" hits="1"/>
						<line number="209" hits="1"/>
						<line number="211" hits="1"/>
						<line number="212" hits="1"/>
						<line number="223" hits="1"/>
						<line number="225" hits="1"/>
						<line number="226" hits="1"/>
						<line number="237" hits="1"/>
						<line number="239" hits="1"/>
						<line number="240" hits="1"/>
						<line number="250" hits="1"/>
						<line number="252" hits="1"/>
						<line number="253" hits="1"/>
						<line number="264" hits="1"/>
						<line number="266" hits="1"/>
						<line number="267" hits="1"/>
						<line number="273" hits="1"/>
						<line number="275" hits="1"/>
						<line number="276" hits="1"/>
						<line number="285" hits="1"/>
						<line number="287" hits="1"/>
						<line number="288" hits="1"/>
						<line number="295" hits="1"/>
						<line number="297" hits="1"/>
						<line number="298" hits="1"/>
						<line number="304" hits="1"/>
						<line number="306" hits="1"/>
						<line number="307" hits="1"/>
						<line number="313" hits="1"/>
						<line number="315" hits="1"/>
						<line number="316" hits="1"/>
						<line number="324" hits="1"/>
						<line number="326" hits="1"/>
						<line number="327" hits="1"/>
						<line number="334" hits="1"/>
						<line number="336" hits="1"/>
						<line number="337" hits="1"/>
						<line number="347" hits="1"/>
						<line number="349" hits="1"/>
						<line number="350" hits="1"/>
						<line number="359" hits="1"/>
						<line number="361" hits="1"/>
						<line number="362" hits="1"/>
						<line number="370" hits="1"/>
						<line number="372" hits="1"/>
						<line number="373" hits="1"/>
						<line number="378" hits="1"/>
						<line number="380" hits="1"/>
						<line number="381" hits="1"/>
						<line number="389" hits="1"/>
						<line number="391" hits="1"/>
						<line number="392" hits="1"/>
						<line number="399" hits="1"/>
						<line number="401" hits="1"/>
						<line number="402" hits="1"/>
						<line number="414" hits="1"/>
						<line number="416" hits="1"/>
						<line number="417" hits="1"/>
						<line number="424" hits="1"/>
						<line number="426" hits="1"/>
						<line number="427" hits="1"/>
						<line number="433" hits="1"/>
						<line number="435" hits="1"/>
						<line number="436" hits="1"/>
						<line number="443" hits="1"/>
						<line number="445" hits="1"/>
						<line number="446" hits="1"/>
						<line number="455" hits="1"/>
						<line number="457" hits="1"/>
						<line number="458" hits="1"/>
						<line number="464" hits="1"/>
						<line number="466" hits="1"/>
						<line number="467" hits="1"/>
						<line number="475" hits="1"/>
						<line number="477" hits="1"/>
						<line number="478" hits="1"/>
						<line number="487" hits="1"/>
						<line number="489" hits="1"/>
						<line number="490" hits="1"/>
						<line number="498" hits="1"/>
						<line number="500" hits="1"/>
						<line number="501" hits="1"/>
						<line number="509" hits="1"/>
						<line number="511" hits="1"/>
						<line number="512" hits="1"/>
						<line number="518" hits="1"/>
						<line number="520" hits="1"/>
						<line number="521" hits="1"/>
						<line number="527" hits="1"/>
						<line number="529" hits="1"/>
						<line number="530" hits="1"/>
						<line number="537" hits="1"/>
						<line number="539" hits="1"/>
						<line number="540" hits="1"/>
						<line number="548" hits="1"/>
						<line number="550" hits="1"/>
						<line number="551" hits="1"/>
						<line number="558" hits="1"/>
						<line number="560" hits="1"/>
						<line number="561" hits="1"/>
						<line number="568" hits="1"/>
						<line number="570" hits="1"/>
						<line number="571" hits="1"/>
						<line number="577" hits="1"/>
						<line number="579" hits="1"/>
						<line number="580" hits="1"/>
						<line number="586" hits="1"/>
						<line number="588" hits="1"/>
						<line number="589" hits="1"/>
						<line number="597" hits="1"/>
						<line number="599" hits="1"/>
						<line number="600" hits="1"/>
						<line number="607" hits="1"/>
						<line number="609" hits="1"/>
						<line number="610" hits="1"/>
						<line number="619" hits="1"/>
						<line number="621" hits="1"/>
						<line number="622" hits="1"/>
						<line number="630" hits="1"/>
						<line number="632" hits="1"/>
						<line number="633" hits="1"/>
						<line number="640" hits="1"/>
						<line number="642" hits="1"/>
						<line number="643" hits="1"/>
						<line number="650" hits="1"/>
						<line number="652" hits="1"/>
						<line number="653" hits="1"/>
						<line number="659" hits="1"/>
					</lines>
				</class>
			</classes>
		</package>
		<package name="core.schema_validation" line-rate="1" branch-rate="0" complexity="0">
			<classes>
				<class name="__init__.py" filename="core/schema_validation/__init__.py" complexity="0" line-rate="1" branch-rate="0">
					<methods/>
					<lines>
						<line number="8" hits="1"/>
						<line number="9" hits="1"/>
					</lines>
				</class>
				<class name="schema_validator.py" filename="core/schema_validation/schema_validator.py" complexity="0" line-rate="1" branch-rate="0">
					<methods/>
					<lines>
						<line number="10" hits="1"/>
						<line number="14" hits="1"/>
						<line number="19" hits="1"/>
						<line number="20" hits="1"/>
						<line number="25" hits="1"/>
						<line number="26" hits="1"/>
						<line number="27" hits="1"/>
						<line number="28" hits="1"/>
						<line number="29" hits="1"/>
						<line number="31" hits="1"/>
						<line number="32" hits="1"/>
						<line number="34" hits="1"/>
						<line number="45" hits="1"/>
						<line number="46" hits="1"/>
						<line number="47" hits="1"/>
						<line number="48" hits="1"/>
						<line number="49" hits="1"/>
					</lines>
				</class>
			</classes>
		</package>
		<package name="core.schema_validation.body_validations" line-rate="0.8333" branch-rate="0" complexity="0">
			<classes>
				<class name="__init__.py" filename="core/schema_validation/body_validations/__init__.py" complexity="0" line-rate="1" branch-rate="0">
					<methods/>
					<lines/>
				</class>
				<class name="body_validations.py" filename="core/schema_validation/body_validations/body_validations.py" complexity="0" line-rate="0.8333" branch-rate="0">
					<methods/>
					<lines>
						<line number="6" hits="1"/>
						<line number="11" hits="1"/>
						<line number="12" hits="1"/>
						<line number="14" hits="1"/>
						<line number="28" hits="1"/>
						<line number="30" hits="1"/>
						<line number="31" hits="1"/>
						<line number="35" hits="0"/>
						<line number="37" hits="1"/>
						<line number="38" hits="1"/>
						<line number="42" hits="0"/>
						<line number="48" hits="1"/>
					</lines>
				</class>
			</classes>
		</package>
		<package name="core.schema_validation.query_parameter_validations" line-rate="1" branch-rate="0" complexity="0">
			<classes>
				<class name="__init__.py" filename="core/schema_validation/query_parameter_validations/__init__.py" complexity="0" line-rate="1" branch-rate="0">
					<methods/>
					<lines/>
				</class>
			</classes>
		</package>
	</packages>
</coverage>
```

**Comment by YLiLarry** [comment] 2020-03-02 19:19
same issue here

**Comment by jhajkom** [comment] 2020-03-05 16:42
I'm having the same issue 😞

**Comment by ryanluker** [comment] 2020-03-15 21:39
@Syntactical01 Thank you for submitting an issue (also @YLiLarry and @jhajkom for mentioning you are having similar problems)!

If you folks could take a look at the example python project and see if the coverage runs for you from within that project, we can get a little closer to figuring this out.

One other thing to try might be to see if you are generating the coverage in a similar way as the example project linked below.

https://github.com/ryanluker/vscode-coverage-gutters/blob/master/example/python/cov.xml

**Comment by jpylypiw** [comment] 2020-06-14 10:58
Hi everyone!
I used the extension for half a year now and it suddenly stopped working. I think the problem is connected to a vscode update.
To help you investigating the issue I tested the cases you wanted to test.

**test results:**
1. I first cloned the whole project on Windows into my git projects folder
1. I added `vscode-coverage-gutters\example\python` to my vscode workspace
1. I opened `python\foobar\tests\bar\a.py` and clicked on `Watch`
1. The coverage is shown perfectly from the example `cov.xml`

![Imgur](https://i.imgur.com/NygKHNE.png)

So I thought about what could be the difference between my project and the example project.

I noticed some differnces:
- my tests run on a linux machine
- my coverage.py version is a little newer: 5.0.3
- I have a different folder structure

For investigation I pasted my `coverage.xml` on Pastebin:
https://pastebin.com/9iFmRLy2

If you need more information, just update the issue :)

**Comment by ryanluker** [comment] 2020-06-15 02:05
@jpylypiw thanks for leaving a comment and all the extra info, this is great!
I will hopefully get a chance to take a look at this tomorrow evening but the coverage version being newer might be one indicator... also do you know which type of xml coverage report you are generating? currently the extension supports clover and cobertura 🤔 .

**Comment by xentux** [comment] 2020-08-09 17:39
Good afternoon!

I don't know if this would help, but I have the same issue, that in "simple" projects everything is shown fine and in more complex projects it doesn't work. Here f.e. in Django projects.
Well, I switched through a few versions of Coverage Gutters and experienced, that the following versions work/not work:

Version / + works, - works not
2.6.0 - 
2.5.1 -
2.5.0 - 
2.4.4 - 
2.4.3 - 
2.4.2 - 
2.4.1 - 
2.4.0 - 
2.3.1 +
2.3.0 +
2.2.2 +
2.2.1 + 
2.2.0 + 
2.1.1 -
2.1.0 - 
2.0.1 +
2.0.0 +
1.3.1 +


I'm running VS Code 1.47.3 on macOS

Coverage.py, version 5.2.1 with C extension


If you need more information, I'll try to help!

**Comment by m0chichan** [comment] 2020-11-05 01:51
> Good afternoon!
> 
> I don't know if this would help, but I have the same issue, that in "simple" projects everything is shown fine and in more complex projects it doesn't work. Here f.e. in Django projects.
...snip
> 
> **Update:**
> I think, I found the issue. When I delete the content of the `<source>` tag, the coverage is shown perfectly.

Confirmed this fix worked for me
VSCode 1.5.0 
vscode-coverage-gutters 2.6.0

I believe this may be related to workspaces issue - https://github.com/ryanluker/vscode-coverage-gutters/issues/252

**Comment by ryanluker** [comment] 2020-12-20 19:33
Thanks for submitting extra info @m0chichan and @xentux !
I will close this in favour of fixing the underlying source issue with https://github.com/ryanluker/vscode-coverage-gutters/issues/252 instead.

**Closed by ryanluker** 2020-12-20 19:33 UTC
Labels: investigating
