### ISSUE TITLE
Using multi root workspace yields 100% cpu usage

### ISSUE THREAD

**Issue by stoffeastrom** [ryanluker/vscode-coverage-gutters#104] opened 2017-11-13 17:50 UTC
When using a multi root workspace I get the picker to choose from 3 lcov files. After choosing one of them the cpu goes crazy and I have to force quit the process which in turns terminates the extension host

**Comment by ryanluker** [comment] 2017-11-13 19:29
@stoffeastrom thanks for the new issue. I was not able to reproduce the 100% cpu on my windows 10 machine with the example node folder and example python folder open in multi root. Can you give me more informantion about OS, vscode version, etc? I will check out this issue on my ubuntu laptop later today to see if it is unix bug.

**Comment by stoffeastrom** [comment] 2017-11-13 21:23
![screen shot 2017-11-13 at 22 21 02](https://user-images.githubusercontent.com/682243/32749850-ff3138ec-c8c0-11e7-92a4-c664926c3cf2.png)

![screen shot 2017-11-13 at 22 21 48](https://user-images.githubusercontent.com/682243/32749877-15dc3844-c8c1-11e7-9cf9-cd1d4ef8a388.png)

Let me know if you need more :)

**Comment by stoffeastrom** [comment] 2017-11-13 21:51
![multi-root-coverage-gutters-issue-mac](https://user-images.githubusercontent.com/682243/32751152-17f31b44-c8c5-11e7-896a-79ff9bb3eef4.gif)

**Comment by ryanluker** [comment] 2017-11-14 01:04
@stoffeastrom thanks for all the extra info! the split pane might be the culprit... what happens if you do watch/display with one pane? Either way this gives me more then enough info to do some tinker on my ubuntu vscode. Worst case is that you might need to wait until i do the performance improvements in #106  for that CPU cost to go down.

**Comment by stoffeastrom** [comment] 2017-11-16 07:51
@ryanluker It doesn't matter if I watch/display with one pane. Same thing the cpu gets choked.

**Comment by ldrick** [comment] 2018-01-05 08:23
Hi @ryanluker ,

I can prove the 100% load on one core looking at htop on Ubuntu 17.10.
Furthermore, on my machine closing vscode normaly doesn't stop the load. I have to force quit vscode in htop.
Working with the exact same directory standalone (not in multi root workspace mode) everything is fine.
I am running vscode 1.19.1.

I'd love to give you every information you could need. Thank you

**Comment by ryanluker** [comment] 2018-01-05 16:01
@ldrick thanks for the further info. Leaning towards trying to find a temporary fix for this one and get it into the 1.3.1 release but the real solution will come from fixing up the underlying structure outlined in #106 . I will message you if I cannot get the example project, in this repo, to be pined to 100% cpu on my ubuntu 17.10 install.

**Comment by ryanluker** [comment] 2018-01-28 22:30
@stoffeastrom @ldrick Sorry for the long turn around on this one, I have narrowed down the issue and plan to get a fix out with 1.3.1. In the meantime you can set ```"coverage-gutters.altSfCompare": false``` (make sure to restart vscode after) to get around the current bug with my extension and vscode workspace api. If you are curious about the bug you can find the offending code here https://github.com/ryanluker/vscode-coverage-gutters/blob/master/src/indicators.ts#L153-L164

**Comment by ryanluker** [comment] 2018-01-28 23:24
@stoffeastrom @ldrick Got this one figured out :smile: you can find the failing test here 386cc73 and the eventual fix here aa09de2

**Closed** 2018-01-29 00:44 UTC
Labels: bug

**Comment by ldrick** [comment] 2018-01-29 08:38
Many thanks @ryanluker, I installed 1.3.1, tested and my CPU seems happy again. :grin:
