### ISSUE TITLE
Remove from right-click menu

### ISSUE THREAD

**Issue by jamesmyatt** [ryanluker/vscode-coverage-gutters#216] opened 2019-04-09 15:22 UTC
**Is your feature request related to a problem? Please describe.**

I don't need quick access to coverage gutter commands. It doesn't need to be in the right click menu; it takes up too much space. The command palette and the status bar are sufficient.

**Describe the solution you'd like**

Option to remove context menu entries.

**Describe alternatives you've considered**

Alternative: Remove context menu entries without option. I assume that some people like it.

**Additional context**

N/A

**Comment by ryanluker** [comment] 2019-04-19 17:39
@jamesmyatt thanks for the issue, in the past you could disable an item in the context menu by using something like:
```
"coverage-gutters.customizable.extension.previewCoverageReport-enabled": false,
```
Which would then remove the context command when the extension started up.
Trying this myself locally and I dont think this works anymore... the problem is there doesn't seem to be an approved way of doing this disabling from what I can see via the docs.
https://code.visualstudio.com/api/references/contribution-points#contributes.menus
https://github.com/Microsoft/vscode/issues/46445

This might be something we have to wait for microsoft to implement sadly...

**Comment by CapsuleMaglev** [comment] 2019-05-06 14:36
Hi @ryanluker! I agree that disabling it via settings.json would be great. 
Are you planning to put it in the extension's settings? (I don't know if it is possible)

I find myself disabling the extension when I am not testing because it takes too much of the context menu.
Thanks!

**Comment by ryanluker** [comment] 2019-06-09 15:59
@CapsuleMaglev it looks like @wenbei999 might have a fix for this here https://github.com/ryanluker/vscode-coverage-gutters/pull/223 if so this will go into the 2.4.0 release :smiley:

**Closed** 2019-06-09 16:12 UTC
Labels: enhancement
